version: '3.7'

services:
  online-shop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online-shop
    ports:
      - '8081:8081'
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/online_shop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1111
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  database:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
    ports:
      - "5432:5432"
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
