name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: 1111
          POSTGRES_DB: online_shop
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Import DB seed data
        run: psql -d postgresql://postgres@localhost/your_test_db_name -f your_seed_data.sql
        working-directory: ./test/data
        env:
          PGPASSWORD: password
      - name: Test some module
        working-directory: ./go/somemodule
        run: go test
        env:
          CI_DB_URL: postgresql://postgres:password@localhost:5432/your_test_db_name

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
        
    - name: Build with Maven
      run: mvn --batch-mode -DskipTests package
      
    - name: Test
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      
    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true 
