name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: 1111
          POSTGRES_DB: online_shop
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
        
    - name: Build with Maven
      run: mvn --batch-mode -DskipTests package
      
    - name: Test
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      env:
          CI_DB_URL: postgresql://localhost:5432/online_shop

    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true 
